[hololens]
package = "holo/lens-helm3/1.2"

[hololens.helm]
namespace = "ingress-nginx"
release_name = "ingress-nginx"

namespace_fill = true

chart_path = "helm-chart"
value_files = [
    "release-values.yaml"
]

[hololens.post_helm]

[hololens.input]
root = "ingress-nginx"
files = "**"

[hololens.output]
merge = "replace"
