[hololens]
package = "holo/lens-helm3/1.3"
before = "k8s-normalize"

[hololens.input]
root = "loki"
files = "**"

[hololens.output]
merge = "replace"

[hololens.helm]
namespace = "loki"
release_name = "loki"

chart_path = "helm-chart"
value_files = [
    "default-values.yaml",
    "provider-values.yaml",
    "release-values.yaml"
]
