apiVersion: v1
data:
  loki-stack-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      version: 1
kind: ConfigMap
metadata:
  labels:
    app: loki-stack
    chart: loki-stack-2.6.1
    grafana_datasource: '1'
    heritage: Helm
    release: loki
  name: loki-loki-stack
  namespace: loki
